// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dinqaqstnouszreqmikv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpbnFhcXN0bm91c3pyZXFtaWt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNTU1ODIsImV4cCI6MjA2ODgzMTU4Mn0.Hi7ogtbeF-cwtqpZKq8MGz3cechHCPDVzxw7Jqs3YRA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});